apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hkedevops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: hkedevops
    spec:
      containers:
      - name: hkedevops
        image: pleungcon.azurecr.io/pleungms/hkedevops:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hkedevops
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hkedevops
